<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bootstrap_package_unal_skin"
 *
 * Auto generated by Extension Builder 2018-11-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Complemento para Bootstrap Package y UNAL Skin',
    'description' => 'esta extension permite unir las funcionalidades de la extension boostrap_package v10 con la extension unal_skin_default.',
    'category' => 'plugin',
    'author' => 'Alexis Ortiz',
    'author_email' => 'eaortiz@unal.edu.co',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99,',
            'bootstrap_package' => '10.0.0-10.0.99,',
            'unal_skin_default' => '0.2.0-0.2.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
